import { useEffect, useState } from 'react';
import { accountApi, type AddressOut, type OrderOut } from '../lib/api/orders';
import { LoadingState } from '../components/StorefrontState';

export default function AccountPage({ onSignIn }: { onSignIn: () => void }) {
  const [addresses, setAddresses] = useState<AddressOut[]>([]); const [orders, setOrders] = useState<OrderOut[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'signedOut' | 'error'>('loading');
  const [addingAddress, setAddingAddress] = useState(false); const [address, setAddress] = useState({ name: '', phone: '', line1: '', city: '', state: '', postalCode: '' }); const [addressError, setAddressError] = useState('');
  useEffect(() => { Promise.all([accountApi.addresses(), accountApi.orders()]).then(([savedAddresses, savedOrders]) => { setAddresses(savedAddresses); setOrders(savedOrders); setState('ready'); }).catch(error => setState(error instanceof Error && error.message === '401' ? 'signedOut' : 'error')); }, []);
  const saveAddress = async () => { if (Object.values(address).some(value => !value)) { setAddressError('Please complete every address field.'); return; } setAddingAddress(true); setAddressError(''); try { const saved = await accountApi.createAddress(address); setAddresses(current => [...current, saved]); setAddress({ name: '', phone: '', line1: '', city: '', state: '', postalCode: '' }); } catch { setAddressError('We could not save this address. Please try again.'); } finally { setAddingAddress(false); } };
  if (state === 'loading') return <div className="min-h-screen bg-[#FAF7F2] pt-28"><LoadingState label="Loading your account…" /></div>;
  if (state === 'signedOut') return <div className="min-h-screen bg-[#FAF7F2] px-4 pt-36 text-center"><h1 className="text-3xl font-medium text-[#2C1810]" style={{ fontFamily: 'var(--font-serif)' }}>Your account</h1><p className="mt-3 text-[#8B6B4A]">Sign in to see saved addresses and order history.</p><button onClick={onSignIn} className="mt-7 rounded-full bg-[#C4622D] px-7 py-3 font-semibold text-white">Sign in with phone</button></div>;
  if (state === 'error') return <div className="min-h-screen bg-[#FAF7F2] px-4 pt-36 text-center text-[#8B6B4A]">We could not load your account right now.</div>;
  return <div className="min-h-screen bg-[#FAF7F2] pt-28"><div className="mx-auto max-w-5xl px-4 py-10"><h1 className="text-4xl font-medium text-[#2C1810]" style={{ fontFamily: 'var(--font-serif)' }}>My account</h1><div className="mt-8 grid gap-8 lg:grid-cols-2"><section className="rounded-2xl border border-[#EDE4D0] bg-white p-6"><h2 className="text-xl font-semibold text-[#2C1810]">Saved addresses</h2>{addresses.map(item => <div key={item.id} className="mt-4 border-t border-[#EDE4D0] pt-4 text-sm text-[#5C3D2E]"><p className="font-semibold">{item.name} {item.isDefault && <span className="text-xs text-[#C4622D]">Default</span>}</p><p>{item.line1}, {item.city}, {item.state} {item.postalCode}</p><p>{item.phone}</p></div>)}<div className="mt-5 grid gap-2 border-t border-[#EDE4D0] pt-4">{Object.entries(address).map(([key, value]) => <input key={key} value={value} onChange={event => setAddress(current => ({ ...current, [key]: event.target.value }))} placeholder={key === 'line1' ? 'Address line' : key === 'postalCode' ? 'PIN code' : key[0].toUpperCase() + key.slice(1)} className="rounded-lg border border-[#EDE4D0] px-3 py-2 text-sm" />)}<button onClick={saveAddress} disabled={addingAddress} className="rounded-full bg-[#C4622D] px-5 py-2.5 text-sm font-semibold text-white">{addingAddress ? 'Saving…' : 'Save address'}</button>{addressError && <p className="text-sm text-[#C4622D]">{addressError}</p>}</div></section><section className="rounded-2xl border border-[#EDE4D0] bg-white p-6"><h2 className="text-xl font-semibold text-[#2C1810]">Order history</h2>{orders.length ? orders.map(order => <div key={order.id} className="mt-4 flex items-center justify-between border-t border-[#EDE4D0] pt-4 text-sm"><div><p className="font-semibold text-[#2C1810]">{order.orderNumber}</p><p className="text-[#8B6B4A]">{order.status.replaceAll('_', ' ')}</p></div><p className="font-semibold text-[#2C1810]">₹{order.totalAmount}</p></div>) : <p className="mt-4 text-sm text-[#8B6B4A]">Your completed orders will appear here.</p>}</section></div></div></div>;
}
