"""add_storefront_models

Revision ID: a85462db2fec
Revises: c00f321d6289
Create Date: 2026-10-01 11:08:48.639919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85462db2fec'
down_revision: Union[str, Sequence[str], None] = 'c00f321d6289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_url', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_settings_id'), ['id'], unique=False)

    op.create_table('homepage_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('emphasis', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eyebrow', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_alt', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homepage_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homepage_campaigns_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_campaigns_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_campaigns_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_campaigns_starts_at'), ['starts_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homepage_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homepage_campaigns_starts_at'))
        batch_op.drop_index(batch_op.f('ix_homepage_campaigns_priority'))
        batch_op.drop_index(batch_op.f('ix_homepage_campaigns_is_active'))
        batch_op.drop_index(batch_op.f('ix_homepage_campaigns_id'))
        batch_op.drop_index(batch_op.f('ix_homepage_campaigns_ends_at'))

    op.drop_table('homepage_campaigns')
    with op.batch_alter_table('brand_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_settings_id'))

    op.drop_table('brand_settings')
    # ### end Alembic commands ###
