"""add_notification_logs

Revision ID: c00f321d6289
Revises: bd0b5eb6abd9
Create Date: 2026-10-01 10:18:24.386213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00f321d6289'
down_revision: Union[str, Sequence[str], None] = 'bd0b5eb6abd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_recipient'), ['recipient'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_status'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_recipient'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_channel'))

    op.drop_table('notification_logs')
    # ### end Alembic commands ###
