"""add_homepage_sections

Revision ID: f5399f52930d
Revises: a85462db2fec
Create Date: 2026-10-01 12:03:59.572793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5399f52930d'
down_revision: Union[str, Sequence[str], None] = 'a85462db2fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('eyebrow', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_alt', sa.String(length=255), nullable=True),
    sa.Column('image_position', sa.String(length=20), nullable=True),
    sa.Column('cta_text', sa.String(length=100), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('collection_slug', sa.String(length=100), nullable=True),
    sa.Column('item_limit', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homepage_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homepage_sections_display_order'), ['display_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_sections_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_sections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_sections_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_sections_section_type'), ['section_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_homepage_sections_starts_at'), ['starts_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homepage_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homepage_sections_starts_at'))
        batch_op.drop_index(batch_op.f('ix_homepage_sections_section_type'))
        batch_op.drop_index(batch_op.f('ix_homepage_sections_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_homepage_sections_id'))
        batch_op.drop_index(batch_op.f('ix_homepage_sections_ends_at'))
        batch_op.drop_index(batch_op.f('ix_homepage_sections_display_order'))

    op.drop_table('homepage_sections')
    # ### end Alembic commands ###
