import { useState } from 'react';
import { XIcon } from './Icons';
import { authApi, type User } from '../lib/api/auth';

export default function AuthModal({ open, onClose, onSignedIn }: { open: boolean; onClose: () => void; onSignedIn: (user: User) => void }) {
  const [phone, setPhone] = useState(''); const [otp, setOtp] = useState(''); const [sent, setSent] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [hint, setHint] = useState('');
  if (!open) return null;
  const send = async () => { setBusy(true); setError(''); try { const response = await authApi.sendOtp(phone); setHint(response.devOtp ? `Local development code: ${response.devOtp}` : 'We sent a code to your phone.'); setSent(true); } catch { setError('We could not send a code. Check the phone number and try again.'); } finally { setBusy(false); } };
  const verify = async () => { setBusy(true); setError(''); try { const response = await authApi.verifyOtp(phone, otp); onSignedIn(response.user); onClose(); } catch { setError('That code could not be verified. Please try again.'); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-[90] flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-label="Sign in"><button className="absolute inset-0 bg-black/40" onClick={onClose} aria-label="Close sign in" /><div className="relative w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl"><button onClick={onClose} className="absolute right-5 top-5 text-[#8B6B4A]"><XIcon size={20} /></button><h2 className="mb-2 text-2xl font-semibold text-[#2C1810]" style={{ fontFamily: 'var(--font-serif)' }}>{sent ? 'Enter your code' : 'Welcome back'}</h2><p className="mb-6 text-sm text-[#8B6B4A]">{sent ? 'Enter the 6-digit code sent to your phone.' : 'Sign in to save your orders and keep your basket across devices.'}</p>{!sent ? <><label className="mb-2 block text-sm font-medium">Phone number</label><input value={phone} onChange={e => setPhone(e.target.value)} placeholder="98765 43210" inputMode="tel" className="w-full rounded-xl border border-[#EDE4D0] bg-[#FAF7F2] px-4 py-3" /><button disabled={busy || phone.length < 10} onClick={send} className="mt-5 w-full rounded-full bg-[#C4622D] py-3.5 font-semibold text-white disabled:opacity-50">{busy ? 'Sending…' : 'Send code'}</button></> : <><label className="mb-2 block text-sm font-medium">One-time password</label><input value={otp} onChange={e => setOtp(e.target.value)} placeholder="123456" inputMode="numeric" maxLength={6} className="w-full rounded-xl border border-[#EDE4D0] bg-[#FAF7F2] px-4 py-3 tracking-[0.4em]" /><p className="mt-3 text-xs text-[#5C7A5A]">{hint}</p><button disabled={busy || otp.length !== 6} onClick={verify} className="mt-5 w-full rounded-full bg-[#C4622D] py-3.5 font-semibold text-white disabled:opacity-50">{busy ? 'Verifying…' : 'Verify and sign in'}</button></>}{error && <p className="mt-4 text-sm text-[#C4622D]" role="alert">{error}</p>}</div></div>;
}
